name: download daily illustration every day
run-name: downloading every day illustration
on:
  schedule:
    - cron: "*/5 * * * *"
env:
  TZ: Asia/Shanghai
  NAME: ${{ github.actor }}

job:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: pull-illustration
      run: |
        echo ${{ github.actor }}